/**
 * Referenzliste – Auszug.
 * Uebernommen aus der Kundenliste (offensichtliche Tippfehler korrigiert).
 * Neue Eintraege einfach ergaenzen;
 * die alphabetische Gruppierung auf der Seite entsteht automatisch.
 */
export const referenzen: string[] = [
  "AGAS Hotel",
  "AHS-Wildau",
  "AMS Airport Service GmbH",
  "Amt zur Regelung offener Vermögensfragen",
  "ANEDIS GmbH Berlin",
  "Antennenbau Fitz",
  "ARRI Schwarzfilm Berlin GmbH",
  "ASB Kreisverband Oberhavel e.V.",
  "Automobilpunkt Ramme",
  "BB Brandenburger Obst GmbH",
  "Berlin Brandenburg Kommunikationstechnik GmbH",
  "Berlin Brandenburgische Akademie der Wissenschaften",
  "Berlin Chemie AG",
  "Berliner Turn- und Sportclub e.V.",
  "Berliner Verkehrsbetriebe",
  "Berufsförderungswerk Brandenburg",
  "Bestattungshaus Rauf",
  "Bezirksamt Marzahn von Berlin",
  "Bezirksamt Spandau von Berlin",
  "BfA Berlin",
  "Bildungszentrum der Finanzverwaltung Königs Wusterhausen",
  "Bildungszentrum Erkner",
  "Brandenburgisches Landesamt für Denkmalpflege",
  "BTI Handwerker-Center Berlin",
  "C & L Haus- und Grundstücksverwaltung GmbH",
  "Cabina GbR – Immobilien & Finanz",
  "Chargeeurs Wool Holding GmbH",
  "Charité Virchow Klinikum Berlin",
  "Cocon Wohnbau GmbH",
  "Conipa Bürosysteme GmbH",
  "CR Capital Airport GmbH & Co. KG",
  "Crewacademy GmbH Berlin",
  "Dahme-Nuthe Wasser- und Abwasserbetriebe",
  "Deutsches Elektronen-Synchrotron DESY",
  "Deutsche Rentenversicherung",
  "Dorband Finanz Berlin GmbH",
  "Eco-Tec GmbH",
  "Eigentümergemeinschaft Ferienhaus Pamir – Norderney",
  "Eisenführ & Speiser Berlin",
  "Ergodat GmbH",
  "EFP Kirchmöser GmbH",
  "Euro Train Berlin/Reinickendorf",
  "Fachhochschule für Wirtschaft in Berlin",
  "FES – Institut für Forschung und Entwicklung von Sportgeräten Berlin",
  "Fressnapf",
  "fm Büromöbel GmbH & Co. KG",
  "Forschungsverbund Berlin e.V. (FVB)",
  "Fortschritte e.V.",
  "Garten- und Landschaftsbau GmbH Wardenburg",
  "GEO Gesellschaft für Immobilientreuhand mbH",
  "Gemeindeamt Bestensee",
  "Gemeindeamt Eichwalde",
  "Gemeindeamt Schulzendorf",
  "Gemeindeamt Schönefeld",
  "Gemeinde Wildau",
  "Gemeindeamt Zeuthen",
  "Germania Express Fluggesellschaft mbH",
  "Green Energy",
  "Gladrow GmbH und Co. KG",
  "GMWGROUP GmbH",
  "GWA-Vermögens-GmbH & Co. KG",
  "Haemato Pharm AG",
  "HCG Treuhand- und Steuerberatungsgesellschaft mbH",
  "IKEA Deutschland GmbH",
  "Immanuel Krankenhaus Berlin",
  "INDAMED",
  "Ingenieurbüro Zammit GmbH",
  "Kassenärztliche Vereinigung Berlin",
  "Kondor Wessels Berlin GmbH",
  "Königliches Forsthaus Bestensee",
  "Küchen Michaelis GmbH & Co. KG",
  "KWP Kümmel, Wiedmann + Partner",
  "KW-TV",
  "Landkreis Dahme-Spreewald",
  "Laxtec GmbH",
  "LDB Phone & Mail Services GmbH",
  "Leibniz-Institut für Gemüse- und Zierpflanzenbau",
  "LICHT Zentrale Lichtgroßhandel GmbH",
  "Lisa Gebäudeservice GmbH",
  "M1 Beauty – Berlin",
  "Magnum AG",
  "Märkische Agrargenossenschaft e.G. Mittenwalde",
  "Maritime Beteiligungen GmbH und Co. KG",
  "Märkischer Geflügelhof Spezialitäten GmbH & Co. KG",
  "MEGAzoo Superstore GmbH",
  "MHT Märkische Hoch- und Tiefbau GmbH",
  "Möbelwerk Niesky GmbH",
  "MS Security Berlin",
  "Naturwacht Brandenburg",
  "Nordprax GmbH Niederlassung Berlin",
  "NOVA Bauen GmbH",
  "NOWEADA Apothekergenossenschaft",
  "Oder-Spree Krankenhaus GmbH Beeskow",
  "Ofen-Fischer GmbH",
  "OMEXOM Umspannwerke GmbH",
  "Orgafox GmbH",
  "Orientalischer Tanz & Kultur Brb e.V.",
  "Patoli Bau GmbH",
  "Physikalisch-Technische Bundesanstalt Berlin",
  "Plan Vital Architektin",
  "Projektlogistik GmbH",
  "Pormedi Soft",
  "Polizeiwache / Rettungsstelle Schönefeld",
  "Polyphon Berlin, Film- und Fernsehgesellschaft mbH",
  "PUNKT1 Reklame & Folientechnik GmbH",
  "PSD Bank Berlin-Brandenburg",
  "REISS Büromöbel GmbH",
  "Rudolf Röser Verlag",
  "Schulverwaltungsamt Königs Wusterhausen / Lübben (LDS)",
  "Schulzendorfer Feuerwehrverein 1903 e.V.",
  "Schwabach – Sanitär Gas Heizung",
  "Schwulenberatung Berlin",
  "Sea Life Deutschland GmbH",
  "Selbsthilfegruppe Multiple Sklerose",
  "Seniorenheim Wildau GmbH",
  "Seniorenstift am Zeuthener See",
  "Seminar- und Tagungshotel *** Superior Bildungszentrum Erkner e.V.",
  "SMB Industrieholding",
  "SN EuroFinanz GmbH",
  "SPD",
  "Sports-inn Waltersdorf",
  "Stadt Erkner",
  "Stadt Königs Wusterhausen",
  "Stadtverwaltung Beelitz",
  "Stadtverwaltung Ludwigsfelde",
  "Stiftung Denkmal für die ermordeten Juden Europas",
  "STL Beleuchtung und Veranstaltungsservice GmbH",
  "Südbrandenburgischer Abfallzweckverband (SBAZV)",
  "Schwarzfilm Berlin",
  "SZK Service Zentrum Kossenblatt GmbH",
  "SZW Servicezentrum Waltersdorf",
  "Tatje KG Berlin",
  "Technische Hochschule Wildau",
  "Technische Objektbetreuung Wardenburg",
  "Technologie- und Gründerzentrum Wildau GmbH",
  "Tourismusverband Dahme-Seen e.V.",
  "Toyota – Autohaus Dietz GmbH",
  "Toyota – Autohaus Zinke GmbH",
  "Trans Tax Consult Berlin",
  "Trend Test GmbH",
  "TUI Reise Center Berlin",
  "UNION Immobilien GmbH",
  "upb GmbH Berlin",
  "Verein zur Förderung der Kinder und Jugendlichen Fichtenwalde e.V.",
  "VHL Vahle & Langholz GmbH",
  "Wasser- und Abwasserzweckverband Blankenfelde-Mahlow",
  "Westfonds Verwaltung GmbH",
  "WH-Erste Grundstücks GmbH & Co. KG",
  "Wildorado – Wildauer Sportbetriebsgesellschaft mbH",
  "Wohn- und Kommunalbauten GmbH Schönefeld",
  "ZAG – Berlin Brandenburg",
  "ZAK – Zeuthener Akademie für Weiterbildung GmbH",
  "Zentral- und Landesbibliothek Berlin",
  "Zeppelin Baumaschinen GmbH",
];

/** Sortierschluessel: Umlaute werden wie ihre Grundbuchstaben einsortiert. */
const UMLAUTE: Record<string, string> = { "Ä": "A", "Ö": "O", "Ü": "U" };

function sortKey(name: string): string {
  // toUpperCase() macht aus "ß" bereits "SS".
  return name.toUpperCase().replace(/[ÄÖÜ]/g, (c) => UMLAUTE[c] ?? c);
}

export type ReferenzGruppe = { letter: string; entries: string[] };

/** Gruppiert (optional gefilterte) Referenzen alphabetisch nach Anfangsbuchstabe. */
export function groupReferenzen(entries: string[]): ReferenzGruppe[] {
  const map = new Map<string, string[]>();

  const sorted = [...entries].sort((a, b) =>
    sortKey(a).localeCompare(sortKey(b), "de"),
  );

  for (const entry of sorted) {
    const first = sortKey(entry).charAt(0);
    const key = /[A-Z]/.test(first) ? first : "#";
    const bucket = map.get(key);
    if (bucket) bucket.push(entry);
    else map.set(key, [entry]);
  }

  return [...map.entries()].map(([letter, list]) => ({ letter, entries: list }));
}
